# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: minimal
day_night: true
font: ''
font_size: l

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: 'Professor of Statistics at the University of Southampton.
Bayesian modeler and author of the book <a href="https://www.taylorfrancis.com/books/mono/10.1201/9780429318443/bayesian-modeling-spatio-temporal-data-sujit-sahu">
Bayesian Modeling of Spatio-Temporal
Data with R.</a> Also author of the R package bmstdr'
twitter: 'SUJITSAHU2'


# Contact (edit or remove options as required)

email: S.K.Sahu@soton.ac.uk
address:
  street: School of Mathematical Sciences
  city: Southampton
  postcode: 'SO17 1BJ'
  country: United Kingdom
  country_code: UK
coordinates:
  latitude: '50.9351'
  longitude: '1.3958'
appointment_url: 'https://calendly.com'
contact_links:
  - icon: twitter
    icon_pack: fab
    name: DM Me
    link: 'https://twitter.com/Sujit_K_Sahu'
  - icon: comments
    icon_pack: fas
    name: Discuss on Forum
    link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: true
highlight_languages:
  - r
math: true
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2022
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: ''
  api_key: ''
  zoom: 15

marketing:
  google_site_verification: 'google-site-verification=UwoBQzfBAF53zBIO50X2cHoOVP_Zgi4pINo__4ffUQM'
  baidu_site_verification: ''
  bing_site_verification: ''

cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: true
